### ISSUE TITLE
Add the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION to the AndroidManifest.xml

### ISSUE THREAD

**Issue by siarhei-luskanau** [android/connectivity-samples#114]
Please add the ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION to the AndroidManifest.xml
It's need for BluetoothLeScanner.startScan()
https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html#startScan(java.util.List%3Candroid.bluetooth.le.ScanFilter%3E,%20android.bluetooth.le.ScanSettings,%20android.bluetooth.le.ScanCallback)

**Comment by linquize** [comment]
This is important. Otherwise beginners won't know why bluetooth scans nothing.
