### ISSUE TITLE
Nearby Connections API not working in some devices

### ISSUE THREAD

**Issue by perugugoutham** [android/connectivity-samples#145]
Tested connections-quickstart sample with Nexus 9 (5.0) and moto g2(6.0 rooted) with both devices in the same WiFi network. Both show success status in advertising and discovery. But doesn't show nearby devices (i.e. fails to go into onEndPointFound() method). The same was the result when tried with Nexus 9 (5.0) and Nexus 9 (7.0). But when tested with Galaxy tab S(5.0.3) with moto g2(6.0 rooted) works good for some time (say 5 times) and later requires reboot of Galaxy device to work good again. 
P.s. My WiFi network do support mDNS discoverability and I've also tested with various other WiFi networks  

May be an update on Nearby API samples is needed.

**Comment by isaidamier** [comment]
Hi All,

We very recently published a codelab that shows[ how to implement the Nearby Connections API](https://developer.android.com/codelabs/nearby-connections?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid#3). I believe it should help resolve your issues. If it doesn't please, reopen with additional comments.

Best,

Isai
