### ISSUE TITLE
Beacon messages cause exception

### ISSUE THREAD

**Issue by ghost** [android/connectivity-samples#159]
NearbyDevices expects a JSON formatted message passed from another Nearby device. However when a beacon attachment is received, the app has no idea what to expect, resulting in an unhandled exception.

Recommendation: add exception handling to onFound() and onLost() functions in MainFragment.java.

If we wanted to get fancy we could add some code to detect whether the message is from a Nearby device or a beacon.

**Comment by isaidamier** [comment]
outdated
