### ISSUE TITLE
Add the ACCESS_COARSE_LOCATION Authority because of Android6.0+ need this to scanf

### ISSUE THREAD

**Issue by siyuhong** [android/connectivity-samples#169]
The comparison between the two is as follows：
https://github.com/android/connectivity-samples/compare/master...siyuhong:test

**Comment by mwallnoefer** [comment]
That's already outdated, since Android > 9 even requires _ACCESS_FINE_LOCATION_: https://developer.android.com/guide/topics/connectivity/bluetooth-le#permissions

**Comment by siyuhong** [comment]
> That's already outdated, since Android > 9 even requires _ACCESS_FINE_LOCATION_: https://developer.android.com/guide/topics/connectivity/bluetooth-le#permissions

Yes , your are true.
