### ISSUE TITLE
BLEGatt Scan Not Working Finding nRf52840

### ISSUE THREAD

**Issue by zawawimanja** [android/connectivity-samples#170]
I already changed the service & characteristic but fail to find.

   /** Nordic UART Service UUID */
    private final static UUID UART_SERVICE_UUID = UUID.fromString("6E400001-B5A3-F393-E0A9-E50E24DCCA9E");
    /** RX characteristic UUID */
    private final static UUID UART_RX_CHARACTERISTIC_UUID = UUID.fromString("6E400002-B5A3-F393-E0A9-E50E24DCCA9E");

This is my uuid. This is my gist. https://gist.github.com/zawawimanja/656dba2c896ed8f277b5d4d8e9d6fbc6

**Comment by Kotuc** [comment]
Hi, I just had the same problem - check out android developer documentation: https://developer.android.com/guide/topics/connectivity/bluetooth-le
You need to use <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" /> which is not in the manifest included in these samples. If this permission is missing, the scan returns no results.

Kind regards
Tomas

**Comment by zawawimanja** [comment]
Tomas I already included in manifest but nothing work.

`
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.bluetoothlegatt"
    android:versionCode="1"
    android:versionName="1.0">

    
    
    
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>

    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  

    <application android:label="@string/app_name"
        android:icon="@drawable/ic_launcher"
        android:theme="@android:style/Theme.Holo.Light">
        <activity android:name=".DeviceScanActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <activity android:name=".DeviceControlActivity"/>
        <service android:name=".BluetoothLeService" android:enabled="true"/>
    </application>

</manifest>
`

**Comment by zawawimanja** [comment]
Anyone have problem after updating gradle to 29. I already solve it.



`
    private static final long SCAN_PERIOD = 10000;

//in oncreate devicescanactivity
        if (ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.ACCESS_FINE_LOCATION}, ACCESS_FINE_LOCATION_PERMISSION);

        }`


then the device will appear.
