### ISSUE TITLE
Connections API: Cannot access received file on Android 10

### ISSUE THREAD

**Issue by cjheyday** [android/connectivity-samples#176]
I am following [this guide](https://developers.google.com/nearby/connections/android/exchange-data) with the goal of transferring an image file which on the receiver side should be uploaded via a REST API.

Android 10 restricts access to public folders like the 'Downloads' folder in which all received files from Nearby Connections API are stored in, in a 'Nearby' folder. It seams to me that the received file is somehow not owned by my app, so I cannot access it.

` File payloadFile = filePayload.asFile().asJavaFile();`

I have a `Payload` object, and as the guide suggests the code above should get the file. Unfortunately the above code returns null when targeting api 29 and running on an Android 10 device. Works fine on earlier Android versions. 

I can get the ParcelFileDescriptor by doing `File payloadFile = filePayload.asFile().asParcelFileDescriptor();` but not sure how to access the file then?

Via the `ParcelFileDescriptor` I have tried reading the file in the following ways but I always get some kind of permission or bad access exception:

`BitmapFactory.decodeStream(FileInputStream(payloadFileDescriptor.fileDescriptor))`
or
`BitmapFactory.decodeFileDescriptor(payloadFileDescriptor.fileDescriptor)`

The file is stored correctly in the Downloads folder as I can see and open it via a file browser app.

Also tried accessing via a content resolver (`MediaStore.Downloads.EXTERNAL_CONTENT_URI` and `MediaStore.Images.EXTERNAL_CONTENT_URI`) but no luck.

A note here is that the files are save with no extension, so maybe that's why Mediastore can't find anything?

I use `"com.google.android.gms:play-services-nearby:17.0.0"`.

As mentioned I really want to receive a file and upload it. Is this totally impossible with Nearby Connections API on Android 10?

**Comment by jacobras** [comment]
Related issue in the Android bug tracker: https://issuetracker.google.com/issues/148641157

**Comment by alexcohn** [comment]
The official recommendation is to set `android:requestLegacyExternalStorage="true"`. Doesn't it resolve your problem?

**Comment by mannprerak2** [comment]
Any updates on this? or any workaround for renaming received files on android 11.

```
android:requestLegacyExternalStorage="true"
```

This doesn't work on Android 11

**Comment by isaidamier** [comment]
It looks like someone already added this to the issue tracker (https://b.corp.google.com/issues/148641157?pli=1). Questions about the samples are best posted here. But for non-sample issues, Stackoverflow and the issue tracker are better locations.
