### ISSUE TITLE
BTLE advertisement fails "data too large" on Android 6.01/SM-G900F

### ISSUE THREAD

**Issue by realososis** [android/connectivity-samples#177]
Project: android-BluetoothAdvertisements
Device with Issue: Samsung SM-G900F with Android 6.0.1

The advertisement fails when the button is clicked with errorCode 1 (ADVERTISE_FAILED_DATA_TOO_LARGE) 

Packet data is reported to exceed 31 bytes. 

However, scanning of other devices works fine with same code running on other devices.

Other devices (Samsung S10 and Huawei P30 Pro, both Android 10) advertise and scan correctly.

    compileSdkVersion 27

    buildToolsVersion "27.0.2"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 27
   
Is the project not backward compatible to API 23 (Mashmallow - Android 6)

Can the project be adapted easily to also support older devices?

**Comment by isaidamier** [comment]
As the error points out, devices aren't required to allocate more than 31 bytes. Still, some devices are free to do so.
