### ISSUE TITLE
Programmatically present the “Nearby Messages” settings page in the device’s settings app.

### ISSUE THREAD

**Issue by GreenRollingHills** [android/connectivity-samples#179]
Hello,

This is an enhancement request.

Can the NearbyMessagesDevices sample provide an example on how to intent to the “Nearby Messages" settings page in the device’s settings app?

As archived [here](https://github.com/googlearchive/android-nearby/issues/65) the intent was previously com.google.android.gms.settings.NEARBY.  The answer also stated that it was going to change. 

I did try recently on a Vankyo tablet running Android 9 but the user gets sent to the “home” page in the device’s settings app.

What is it current intent?

Thanks,

**Comment by isaidamier** [comment]
Users can manager through Settings > Apps & Notifications > Permission Manager. If I have misunderstood your question, would you please elaborate on what you are trying to achieve? Provide step by step UX instruction so we can see what you mean.

(please feel free to reopen the issue if not yet resolved)
