### ISSUE TITLE
BluetoothLeGatt: How to read full length of data when my data contain 0x0a and 0x0d?

### ISSUE THREAD

**Issue by BennyLWK** [android/connectivity-samples#185]
Android OS: 10 Samsung A70
I am able to connect to the device correctly and it can receive the characteristic correctly without any errors. But it gets something wrong when the received data contain 0x0a and 0x0d.

For example, the device sends the data as 0b710a6000179c21346fb23feec651bc to the mobile app. The app will receive the message as below. The app split the data into 2 data.

D/BluetoothLeService: Receive Data = 0B71
D/BluetoothLeService: Receive Data = 6000179C21346FB23FEEC651BC

This is the log message from the function broadcastUpdate

private void broadcastUpdate(final String action,
                             final BluetoothGattCharacteristic characteristic) {
    final Intent intent = new Intent(action);

    if (UUID_HEART_RATE_MEASUREMENT.equals(characteristic.getUuid())) {
        ...
    } else {
        // For all other profiles, writes the data formatted in HEX.
        final byte[] data = characteristic.getValue();
        if (data != null && data.length > 0) {
            String hexData=DeviceControlActivity.bytesToHex(data);
            Log.d(TAG, "Receive Data = "+hexData);
            intent.putExtra(EXTRA_DATA, data);
        }
    }
    sendBroadcast(intent);
}

Is there any way to receive the full length of data when it contains 0x0A and 0x0D? So the app can receive full data as 0B710A6000179C21346FB23FEEC651BC. Please advice. Thank you

**Comment by Vandana0** [comment]
Can i get the write/notify code?
