### ISSUE TITLE
Dangling bluetooth connection

### ISSUE THREAD

**Issue by andersgjetting** [android/connectivity-samples#198]
On iOS its possible to ask the operating system to connect to a specific bluetooth device and wake up your app, when the bluetooth device / connection is available. Is there any way to do this on the android. I have tried scanning with a pending intent and a broadcast receiver which then starts a job. It works as long as the mobile device is active, but as soon as the mobile device enters doze mode idle it stops working. Is there any way to get around

**Comment by pablichjenkov** [comment]
Have you tried having a Foreground Service in your App so it keeps your App always alive.

**Comment by isaidamier** [comment]
Hi andersgjetting,

Have you had a chance to read [our latest blog post on Nearby Messages](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9)?

"""
The Nearby Messages API can run in foreground mode or in background mode. In background mode, there is little battery cost as the API only scans for a few seconds when you turn your screen on. However, in foreground mode, the API will scan all the time, meaning that if the screen is off and Nearby Messages discovers a beacon, it ends up waking up the application processor and those wake-ups are quite costly — often up to 2.5X to 3.5X the normal battery consumption rate.
"""
