### ISSUE TITLE
Crash "invalid channel for service notification"

### ISSUE THREAD

**Issue by KrechkoMichael** [android/connectivity-samples#2]
on Android 9 after tap "Broadcast Device" control:
"android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0x00000000 vis=PRIVATE)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1760)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)"

**Comment by albvol** [comment]
Have you found a solution?

**Comment by albvol** [comment]
[UPDATE] for others wondering how to solve the issue, the solution is described here: [https://github.com/android/connectivity-samples/issues/113#issuecomment-368886537](url)

Be aware that in some cases you should add in the manifest: 
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`

**Comment by gravityklz** [comment]
> 
> 
> Have you found a solution?

well I know that the app doesn't ask you for  access of location, so when you select a device it would crash.  So I went into app info and turned on location access and it would go to the next screen, then you select the 3 dots in the upper right corner and select connect then thats when mine crashes, if you look on logcat it says something about a null pointer exception right about this method (public boolean onOptionsItemSelected), when I looked that up they talked about the menu refresh which is set to null in the program..So thats the long version if you figure out how to get rid of the null pointer exception please let me know.
