### ISSUE TITLE
Bluetooth LE not showing(Scanning?) list of BLE device in Note 10+

### ISSUE THREAD

**Issue by Laren2121** [android/connectivity-samples#203]
I was using this in galaxy s4 and it was working fine. But I want this repo to work on all android phones (newer ones). Please guide me to solve this problem.
 I have been following [https://stackoverflow.com/a/37423244/2585501](https://stackoverflow.com/a/37423244/2585501) but I didn't have any success with it.

**Comment by Laren2121** [comment]
It worked... 
follow this link [https://github.com/android/connectivity-samples/issues/34](https://github.com/android/connectivity-samples/issues/34). I added 
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/> 

code in AndroidManifest.xml and this code under DeviceScanActivity
int permissionCheck = ContextCompat.checkSelfPermission(this, Manifest.permission.ACCESS_FINE_LOCATION);
if (permissionCheck != PackageManager.PERMISSION_GRANTED){
if (ActivityCompat.shouldShowRequestPermissionRationale(this, Manifest.permission.ACCESS_FINE_LOCATION)){
Toast.makeText(this, "The permission to get BLE location data is required", Toast.LENGTH_SHORT).show();
}else{
requestPermissions(new String[]{Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_FINE_LOCATION}, 1);
}
}else{
Toast.makeText(this, "Location permissions already granted", Toast.LENGTH_SHORT).show();
}

**Comment by isaidamier** [comment]
Sounds like this issue was resolved? Please reopen with additional details if that's not correct.
