### ISSUE TITLE
Why Google Nearby Connections needs ACCESS_COARSE_LOCATION and/or ACCESS_FINE_LOCATION permissions?

### ISSUE THREAD

**Issue by ImTema** [android/connectivity-samples#204]
I googled very hard and still no explanations "why?" these permissions are needed to establish **offline**(no internet) connection between devices. I have simple app that requires only p2p-star strategy to exchange data between devices in master-slave pattern and I have troubles explaining to my users why my app needs them. "Just because lib said so. That's why".

Official documentation also said nothing to me.

"_A primary goal of this API is to provide a platform that is simple, reliable, and performant. Under the hood, the API uses a combination of **Bluetooth, BLE, and Wifi hotspots**, leveraging the strengths of each while circumventing their respective weaknesses. This effectively abstracts the vagaries of Bluetooth and Wifi across a range of Android OS versions and hardware, allowing developers to focus on the features that matter to their users._"

PS: as I know ACCESS_COARSE_LOCATION and ACCESS_FINE_LOCATION are about GPS.

**Comment by isaidamier** [comment]
I hope this answers your question: https://developer.android.com/about/versions/12/features/bluetooth-permissions
