### ISSUE TITLE
Nearby Connections no option for Earshot distance?

### ISSUE THREAD

**Issue by danielkp1234** [android/connectivity-samples#205]
So I am working with trying to transfer data between two phones with Google Nearby Connections.

For example, say I want to transfer a variable from each phone to another and then show a toast containing the text from the other phone.

I have been looking into the Connections API but I can't seem to limit it to when two phones are really close to each other. I have seen that the Nearby Messages API has an Earshot distance option.

But there isn't an option for earshot distance in the Nearby Connections API since the Nearby messages API doesn't seem to contain what I need to make something like the example above work.

Hope you can help me :)

**Comment by isaidamier** [comment]
Hi danielkp1234, The ultrasonic API has been removed from Nearby and so earshot is no longer available for either Messages or Connections.
