### ISSUE TITLE
BLE scan doesn't find any peripheral

### ISSUE THREAD

**Issue by santaanto** [android/connectivity-samples#226]
Hello
I am using the BluetoothLeGatt application (https://github.com/android/connectivity-samples/tree/main/BluetoothLeGatt) , just to test it I have nearby a phone active as peripheral broadcasting gatt service and some characteristics ( I used the official example available ) and anyway I know there are other devices that can be seen nearby as I tried with a BLE scanner downloaded from Googlplay. 
However the BLE scan from this BluetoothLeGatt application doesn't return anything found. On Android studio there aren't any error messages , just the scan stops without any result.
I am using Samsung S10e. 
what could I be missing ?

thank you

**Comment by MIGUE1999** [comment]
You have to give the ACCES_FINE_LOCATION permission in the manifest.xml and activate android ubication

**Comment by santaanto** [comment]
thank you , I see that ACCES_FINE_LOCATION is in the manifest.xml.
How to activate android ubication ?
the only way I found is going on the mobile phone settings apps permissions and manually allow the location permission that by default is denied. 
It then works. Is this because I am installing the app through Android Studio or is it denied by default for other reason ?

**Comment by santaanto** [comment]
Hello, thank you for the code.
Could you explain me how to embed this code in the com.example.android.bluetoothlegatt example from this repository ?
There are two OnCreate() functions. Which one is the correct to use ?One is in DeviceScanActivity; the other is in DeviceControlActivity. I can't find MainActivity in this example, why ?
How can I link the Manifest object you use in the code above to the Manifest file in the app ?

thank you

**Comment by hassandraga** [comment]
I already created a pull request for that, you can see the implementation https://github.com/android/connectivity-samples/pull/231/commits/97d48ac4438467792ad26d0aac5c9bcc24c41d63

The DeviceScanActivity is acting like main activity, because it's flagged in launcher.

**Comment by santaanto** [comment]
thank you! That's useful
