### ISSUE TITLE
Android BLE Scan Callback is not called after scanning for BLE devices

### ISSUE THREAD

**Issue by jaballogian** [android/connectivity-samples#238]
Hello, I tried implementing all BLE documentations from Android but the ```BLE Scan Callback``` was not called after scanning for BLE devices.
I already asked the question here https://stackoverflow.com/questions/68036622/android-ble-scan-callback-is-not-called-after-scanning-for-ble-devices but there has no correct answer yet.

**Comment by isaidamier** [comment]
Have you had a look at the [latest Bluetooth sample](https://github.com/android/connectivity-samples/tree/main/BluetoothAdvertisementsKotlin)? It might help you resolve your issue. Also we are publishing a[ blog post series](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9) that may be helpful

**Comment by jaballogian** [comment]
Thanks for the information.

I tried to clone the repository, then build and run the app to my phone.

But there was an error in the code:

```
e: E:\android\BluetoothSamples\BluetoothAdvertisementsKotlin\app\src\main\java\com\example\bluetoothadvertisements\MainActivity.kt: (39, 47): Unresolved reference: toolbar
```

I checked the ```activity_main.xml``` file and there is no ```id``` with the name ```toolbar```.

**Comment by jaballogian** [comment]
I tried to copy and paste some code from ```ScannerFragment.kt``` from the example app then convert it to ```Java``` and it worked.

Thanks a lot.
