### ISSUE TITLE
NearbyMessage API not working in some devices with Android 11

### ISSUE THREAD

**Issue by VivekMakwana24** [android/connectivity-samples#242]
Hello,

I have used NearByMessage API in one of my projects, It's working in many devices which has android version <= 10.
Unfortunately it;s not working in Some devices with Android 11, I am able to publish and subscribe successfully but not able to fetch other device's data.

Does anyone faced this issue?

**Comment by isaidamier** [comment]
Hi could you share more details about the particular Android devices you are testing with, such as make and model?

**Comment by VivekMakwana24** [comment]
![Screenshot from 2021-07-19 09-38-02](https://user-images.githubusercontent.com/48508009/126101805-aeac9545-b39e-4fc9-8686-eb50bf980e17.png)
![Screenshot from 2021-07-19 09-39-45](https://user-images.githubusercontent.com/48508009/126101809-6fe4f487-cb79-46df-81d1-1d0d02e0a5e7.png)
![Screenshot from 2021-07-19 09-40-06](https://user-images.githubusercontent.com/48508009/126101810-cbfdca6f-855e-4bc8-9bb9-0c553890045a.png)



Hello @isaidamier 

Thanks for the response, Hope you are doing well!

This is my code you can check, I am able to connect 2 devices but my client is facing an issue connecting them.
He is using 
- Google Pixel 2XL (Android 11)
- POCO X3 NFC (Android 11)

From my block of code, He is able to print the logs such as ("nearby Published successfully.") and ("nearBy Subscribed successfully.")

But it never goes inside the onFound method of MessageListener()

Could you please guide me to the solution , It would be very helpful

Thank you.

**Comment by VivekMakwana24** [comment]
Hello @isaidamier 

Have you checked it ?

**Comment by VivekMakwana24** [comment]
Is there anything related to **"data protection directive in EU / Germany"**
As in Germany, he is not able to use this API properly.

**Comment by VivekMakwana24** [comment]
Hello

Devices with no google play services are facing this issue of not being able to exchange information using Nearby Message API.

**Devices:**
Xiaomi Redmi Note 10X
POCO X3 NFC


Why it is not consistent even for other devices. It sometimes works sometimes doesn't work?

**Comment by isaidamier** [comment]
Hi Vivek,

Sorry for not being able to respond sooner.  Because Nearby is part of the Google Play service, it will not work on devices that do not support Google Play service. Also we recently [published a codelab](https://developer.android.com/codelabs/android-nearby-messages?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid#0) that shows how to best use the Nearby Messages API. Please take a look there for more details. I hope that helps resolve any issue. If not please feel free to reopen.

Best,

Isai
