### ISSUE TITLE
NearbyConnections API startDiscovery always failed

### ISSUE THREAD

**Issue by supervital** [android/connectivity-samples#243]
Hello,

After some time of testing Nearby Connections API, I faced the case when **startDiscovery()** is always failed with error code 8034: MISSING_PERMISSION_ACCESS_COARSE_LOCATION. But all the permissions are granted. At the same time **startAdvertising()** works like a charm (same app, same granted permissions). The Nearby worked well but after some time **startDiscovery()** started to fail. Looks like it's an API bug. Used strategy - Strategy.P2P_POINT_TO_POINT.

Example application (Rock-Paper-Scissors) also failed. I changed the example a bit - one device is Discovering, another Advertising.

Have no idea how to fix it. 

Thanks.

**Comment by supervital** [comment]
I found the reason when **startDiscovery()** is always failed - the Location option from the Android Setting was turned off manually. I supposed that the Nearby Connections API should turn on all the necessary options and turn off after the session.

**Comment by supervital** [comment]
Looks like I should turn Location settings on programmatically.

**Comment by isaidamier** [comment]
Hi supervital,

Sorry to hear about your experience. [Location](https://developer.android.com/training/location/permissions) is a dangerous permission and therefore only the user can turn it on. As a developer, you must declare it in your manifest and you must request it at runtime. We recently [published a codelab](https://developer.android.com/codelabs/nearby-connections?hl=en&continue=https%3A%2F%2Fcodelabs.developers.google.com%2F%3Fcat%3Dandroid#0) that walks you through using the Nearby Connections API. Please take a look there for more details.

Best,

Isai
