### ISSUE TITLE
Find Opponent button gives error in RockPaperScissorsKotlin 

### ISSUE THREAD

**Issue by ShoaibKakal** [android/connectivity-samples#272]
```
E/GoogleApiManager: Failed to get service from broker. 
    java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.google.crossdevice.sample.rps, sha256=[167f3f67569c9588c936653e5f528bc756b21afff40c9afb5376e59bf81a797a], atk=false, ver=222658044.true (go/gsrlt)
```

**Comment by rawmain** [comment]
Hello @ShoaibKakal 

If you have successfully enrolled in the **[Google Play Services Beta program](https://developers.google.com/android/guides/beta-program)**, check the GMS version you're using on your test-device/environment = now you should be using a 22.32.55 release build for GMS.

For instance, no issues here on my ARM test-devices with RPS Kotlin Demo & the following GMS Beta build : 

```
package      : com.google.android.gms
version      : 22.32.55 (040408-468276081)
released     : August 24th, 2022
architecture : arm64-v8a + armeabi-v7a
minimum SDK  : API level 23 - Marshmallow 6.0
Screen DPI   : 480 dpi
```

**Comment by whitevegagabriel** [comment]
@ShoaibKakal were you able to resolve this issue?

**Comment by ShoaibKakal** [comment]
Yes @whitevegagabriel by following @rawmain comment.
