### ISSUE TITLE
DeviceControlActivity attempts to read value for any characteristic

### ISSUE THREAD

**Issue by dweebo** [android/connectivity-samples#46]
It seems to me on lines 129 and 139 of DeviceControlActivity.java that the code means to only perform logic if the characteristic properties include READ or NOTIFY.  Instead of bitwise or, I think it should be bitwise and, like this:

```
if ((charaProp & BluetoothGattCharacteristic.PROPERTY_READ) > 0)
```

**Comment by Vandana0** [comment]
Can i get code for Write/Notify? @tjohns @agueroveraalvaro
