### ISSUE TITLE
Coarse location permission

### ISSUE THREAD

**Issue by codingjeremy** [android/connectivity-samples#57]
<a href="https://github.com/Shakenbeer"><img src="https://avatars2.githubusercontent.com/u/5087719?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Shakenbeer](https://github.com/Shakenbeer)**
_Sunday Apr 08, 2018 at 07:24 GMT_
_Originally opened as https://github.com/android/android-BluetoothLeGatt/pull/53_

----

In real life, most of Bluetooth LE devices associated with a location, so without this permission, the sample shows nothing in most cases.
Also, duplicate check removed.

----

_**[Shakenbeer](https://github.com/Shakenbeer)** included the following code: https://github.com/android/android-BluetoothLeGatt/pull/53/commits_

**Comment by codingjeremy** [comment]
<a href="https://github.com/harounhajem"><img src="https://avatars3.githubusercontent.com/u/17148955?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [harounhajem](https://github.com/harounhajem)**
_Saturday Nov 24, 2018 at 22:58 GMT_

----

Had this error, and were about to put up a PR. They should merge this.

**Comment by codingjeremy** [comment]
<a href="https://github.com/SamuelBrucksch"><img src="https://avatars0.githubusercontent.com/u/8776268?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [SamuelBrucksch](https://github.com/SamuelBrucksch)**
_Friday Feb 15, 2019 at 12:27 GMT_

----

I also had this problem on Android 6. Thanks for opening a PR. Helped me out!

**Comment by isaidamier** [comment]
Please see: https://developer.android.com/about/versions/12/features/bluetooth-permissions
