### ISSUE TITLE
Sending reciving data

### ISSUE THREAD

**Issue by dd790** [android/connectivity-samples#73]
Hi sorry for my noob question

How can i use send / receive data from this app?

Im working on tic-tac-toe game over bluetooth (as a school project) and i need to send / receive  game state after player move. That part was easy now im working how to get that info send to other device.

If i can ask to expain it in realy easy way.

Thx

**Comment by isaidamier** [comment]
This app is doing precisely what you wish to do. Let us know if that answered your question: https://github.com/android/connectivity-samples/tree/main/NearbyConnectionsRockPaperScissors
