### ISSUE TITLE
Partially working of sample code

### ISSUE THREAD

**Issue by abrarul312** [android/connectivity-samples#74]
iam using this code for my application,  broadcast in working but the problem is device not working on BluetoothDevice .ACTION_FOUND instead of that executing BluetoothAdapter_ACTION_DISCOVERY_FINISHED is executing i tried many times given all permissions and made devices discoverable also. but still not working. Please help me here is my code....

**import android.app.ProgressDialog;
import android.bluetooth.BluetoothAdapter;
import android.bluetooth.BluetoothDevice;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

import java.util.ArrayList;

public class SelectPrinterActivity extends AppCompatActivity {

    ArrayList<String> device_list;
    ArrayAdapter<String> adapter;
    ListView printer_list;
    ProgressDialog progressDialog;
    BluetoothAdapter bluetoothAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_select_printer);

        bluetoothAdapter=BluetoothAdapter.getDefaultAdapter();
        diDiscovery();

        printer_list=findViewById(R.id.printer_list);
        device_list=new ArrayList<>();
        device_list.clear();
        adapter=new ArrayAdapter<String>(getApplicationContext(),R.layout.device_name);

        IntentFilter filter=new IntentFilter(BluetoothDevice.ACTION_FOUND);
        this.registerReceiver(receiver,filter);

        filter=new IntentFilter(BluetoothAdapter.ACTION_DISCOVERY_FINISHED);
        this.registerReceiver(receiver,filter);

    }

    private void diDiscovery()
    {
        if(bluetoothAdapter.isDiscovering())
        {
            bluetoothAdapter.cancelDiscovery();
        }
        bluetoothAdapter.startDiscovery();

        progressDialog=new ProgressDialog(this);
        progressDialog.setMessage("Scanning..Devices");
        progressDialog.setCancelable(false);
        progressDialog.show();
    }

    BroadcastReceiver receiver=new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            String action=intent.getAction();
            if(BluetoothDevice.ACTION_FOUND.equals(action))
            {
                progressDialog.dismiss();
                BluetoothDevice device=intent.getParcelableExtra(BluetoothDevice.EXTRA_DEVICE);
                adapter.add(device.getName());
            }
            else if(BluetoothAdapter.ACTION_DISCOVERY_FINISHED.equals(action))
            {
                progressDialog.dismiss();
                adapter.add("no devices found");
                Toast.makeText(SelectPrinterActivity.this, "No devices Found", Toast.LENGTH_SHORT).show();
            }
        }
    };

}**

**Comment by isaidamier** [comment]
Have you been able to resolve the issue you encountered? If not maybe our [recently updated sample](https://github.com/android/connectivity-samples/tree/main/NearbyMessagesDevices) can help. Also our latest [blog post series on Nearby](https://medium.com/androiddevelopers/better-physical-stories-with-googles-nearby-apis-280be707bbf9)

**Comment by isaidamier** [comment]
Please feel free to reopen if issues not resolved
